version: '3.8'

services:
  php-container:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      PHP_IDE_CONFIG: "serverName=docker-cli"
